### ISSUE TITLE
Let's use inheritance for Skippable

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#122]
Writing the parser would be easier if we had

```c++
[Skippable] SkippableFunctionDeclaration: EagerFunctionDeclaration {
  // Implicit skippable field.
  // Nothing else to add
}
```

So let's make this possible.

**Comment by arai-a** [comment]
given that now `[Lazy]` is applied to field, not interface, I'd propose closing this issue.
or perhaps there's similar benefit for field?

**Comment by Yoric** [comment]
You're right.
