### ISSUE TITLE
Skip string-table entries for short strings

### ISSUE THREAD

**Issue by kannanvijayan** [binast/binjs-ref#134]
This thought came out of the encoder I'm writing for the dictionary-subtree compression I'm working on.  I'm at the point where I can produce output for some files (but there are a few crashes on some files due to bugs, so still in progress).

When looking through the raw generated output (hexdump) of a file, I noticed that most of the string table was full of single-character entries.  These were all for minified identifiers of 1 character.

We gain zero benefit from putting these in the string table, it adds 2 bytes of far-removed redundancy (string table is far away from most of code) for every unique identifier in the code.

It also saves nothing in the content because we need to use a byte to reference the table entry anyway.

Short simple identifiers (e.g. of lengths <= 2, ascii-only) should have a special encoding that emits the identifier directly into the tree-data stream (e.g. using a varnum-like variable-length encoding since identifier character set gives us extra bits at the top of a byte).

I suspect this can eliminate a lot of redundancy.  I'm currently modifying my encoder to use this technique, but the method itself is independent and can be applied to any of the our current encoding strategies.

Yoric, do you want to try this on the encoders you're working with?

**Comment by Yoric** [comment]
Yep, I'll try that.

**Comment by Yoric** [comment]
I'm a bit skeptic about this. I'm afraid that this will actually make the result harder to compress with a further gzip/brotli. I'm rather investigating context-aware indexing that I hope will let us fit more identifiers/strings within fewer bytes.

**Comment by Yoric** [comment]
After a 1:1, we concluded that it wasn't worth the trouble.
