### ISSUE TITLE
Define the format, metadata for shared probability tables, strings, etc.

### ISSUE THREAD

**Issue by dominiccooney** [binast/binjs-ref#164]
The binast-node repo and this repo's entropy branch are experimenting with entropy-based encoding methods. To achieve better file sizes, there's an idea to share probability tables and other data between files in a corpus. We need to define what this format is.

Because a lot of data in this file depends on the grammar, possibly the grammar should be part of this "dictionary" file, or the dictionary file should refer to the grammar.

Because a given file would not be usable with a different dictionary, it probably makes sense for a file to have metadata pointing to its dictionary as opposed to/in addition to out of band metadata such as a HTTP header.

**Comment by Yoric** [comment]
Discussion moved [here](https://github.com/binast/container-format-spec/issues/7).

**Comment by Yoric** [comment]
> Because a given file would not be usable with a different dictionary, it probably makes sense for a file to have metadata pointing to its dictionary as opposed to/in addition to out of band metadata such as a HTTP header.

That specific point moved [here](https://github.com/binast/container-format-spec/issues/4).
