### ISSUE TITLE
sort GRAMMAR table and STRINGS table items

### ISSUE THREAD

**Issue by arai-a** [binast/binjs-ref#171]
looks like the order of items in GRAMMAR table and STRINGS table is random.
it should be sorted in consistent order (maybe just alphabetically)

**Comment by arai-a** [comment]
as far as I can see, the table entries are actually sorted, but it's sorted by the number of uses, which can be same for multiple entries, and the order between entries with same number of uses is undefined.
we should introduce the rule about the order between them, in order to keep the output same for multiple encoding execution.

**Comment by Yoric** [comment]
Good idea.
