### ISSUE TITLE
floating point number is rounded incorrectly

### ISSUE THREAD

**Issue by arai-a** [binast/binjs-ref#191]
source
```
  print(1834995.3515519998);
```

binjs_dump result for number
```
   11 : 08                      # LiteralNumericExpression {
      :                         # .value
   12 : d7 4f ff 59 f3 ff 3b 41 # float=1834995.351552
      :                         # }
```

**Comment by Yoric** [comment]
Do you know at which stage it is rounded?

**Comment by arai-a** [comment]
so, what we can do is either:
  a) fix the json crate's implementation of Number => f64
  b) extract the info from Number::as_parts and calculate on our side

but I'm not sure if the `Number` representation itself can represent the entire 64-bit floating point.
(for this case, it contains entire digits tho)

**Comment by arai-a** [comment]
I guess we can just extract the info and use String.parse::<f64>()
I'll try.
