### ISSUE TITLE
add a command to convert possibly-invalid JSON to binjs file

### ISSUE THREAD

**Issue by arai-a** [binast/binjs-ref#194]
We need a way to create an invalid-file testcase reliably and automatically, which is usable across format version bump, to test implementation against invalid input efficiently.

I think XML is sufficient to represent most possible format-independent invalid structure,
such like SyntaxError or something.

If such XML can be converted to other format without performing error check, that can be used as a testcase.

**Comment by arai-a** [comment]
possible use case is,

  1. convert .js to XML
  1. apply modification based on XML pattern matching and modification rule
  1. convert XML to .binjs file
  1. feed the result .binjs file to implementation

in this way, we can get invalid file which represents the same structure, across format version bump,
just by preparing the input .js file and the XML modification rule

**Comment by Yoric** [comment]
Good idea.

**Comment by arai-a** [comment]
for the following reasons, I'm going to use JSON instead:
  - we need another implementation of serializer/deserializer to handle lone surrogate
    - especially WTF-8 support, either with `rust-wtf8` or our `escaped_wtf8`
  - JSON is better for automation, when applying filter
  - JSON is simpler for implementing serializer/deserializer
