### ISSUE TITLE
Add newline characters to container header

### ISSUE THREAD

**Issue by zealousidealroll** [binast/binjs-ref#196]
The proposed [BinAST container format](https://github.com/binast/binjs-ref/issues/13) starts with the word "BINAST", then a version number, then the rest is the payload. The PNG format, for comparison, has a much more complicated [header](https://en.wikipedia.org/wiki/Portable_Network_Graphics#File_header):

> Values | Purpose
> -- | --
> 89 | Has the high bit set to detect transmission systems that do not support 8 bit data and to reduce the chance that a text file is mistakenly interpreted as a PNG, or vice versa.
> 50 4E 47 | In ASCII, the letters PNG, allowing a person to identify the format easily if it is viewed in a text editor.
> 0D 0A | A DOS-style line ending (CRLF) to detect DOS-Unix line ending conversion of the data.
> 1A | A byte that stops display of the file under DOS when the command type has been used—the end-of-file character.
> 0A | A Unix-style line ending (LF) to detect Unix-DOS line ending conversion.

I think that BinAST should include similar "check bytes" in its header, particularly the newline characters (to detect if it got line-ending converted) and the `1A` byte (not because we're worried about DOS, but because normal text files never contain that byte, it helps tools like `grep` avoid accidentally interpreting a binast file as ASCII, especially since they will often get served with a `.js` extension).

**Comment by Yoric** [comment]
I have no problem with this, but is ASCII conversion still a thing?

**Comment by zealousidealroll** [comment]
If I was going to make a specific proposal, it would probably be to essentially adopt the PNG header, except with the DOS EOF replaced with a NUL:

Values | Purpose
-- | --
89 | Has the high bit set, but is not part of a valid multi-byte UTF-8 sequence, to prevent a BinAST file from being misinterpreted as a text file, or vice-versa.
42 4A 53 | In ASCII, the letters BJS, allowing a person to identify the format easily if it is viewed in a text editor.
0D 0A | A DOS-style line ending (CRLF) to detect DOS-Unix line ending conversion of the data.
00 | A zero byte, to detect transports that treat NUL as a sentinel, and further ensuring that BinAST files are not treated as text.
0A | A Unix-style line ending (LF) to detect Unix-DOS line ending conversion.

I also specifically used NUL because [ripgrep](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering) and [git](https://stackoverflow.com/a/6134127) both explicitly use the presence of NUL to identify a file as "binary".

I also specifically want to keep the magic number 8 bytes in size, so that it can be checked with a single compare instruction, instead of having to be checked one-byte-at-a-time. It should also fit in the filesystem's inline portion, though AFAICT, the inline portion of a file is usually bigger than that, like [128 bytes](https://harperdbhelp.zendesk.com/hc/en-us/articles/360007127654-Configuring-inline-data-in-the-ext4-Filesystem), [52 bytes](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.ioea700/ioea7d0091004053.htm), or [800 bytes](https://en.wikipedia.org/wiki/NTFS#Attribute_lists,_attributes,_and_streams)... yeah, it varies pretty widely between filesystems, but always bigger than 8.

**Comment by Yoric** [comment]
That makes sense.

**Comment by Yoric** [comment]
I'm handling this in #257.
