### ISSUE TITLE
Design a compression test for entropy

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#199]
For the moment, we don't have a good way to test how well we compress data with entropy coding.

Perhaps we could do something along the lines of:

- obtain two versions of the facebook snapshot, taken from different versions of the facebook chat;
- extract the dictionary (strings + prediction tables) from v1;
- test compression with v2;
- compare v2 compressed with the dictionary with gzip/brotli/...

@dominiccooney What do you think of this protocol? Could you handle this?

**Comment by dominiccooney** [comment]
I have done this and reported results in snippets and email. I'm happy to provide updated results when necessary, just get in touch.

**Comment by Yoric** [comment]
Thanks, @dominiccooney. Could you possibly collate all the information somewhere (here?) for future reference? This will make it easier for us to find it when needed.

**Comment by Yoric** [comment]
Ideally, I'd like to automate this, so that we could just run a single command and be able to test improvements or regressions immediately.

**Comment by Yoric** [comment]
Moving things to Entropy 0.3, as this apparently needs better extensibility.

**Comment by Yoric** [comment]
@dominiccooney Do you think you'll be able to land this test once we have landed Entropy 0.3? (that's going to happen hopefully today)

**Comment by Yoric** [comment]
This was basically solved by #276.
