### ISSUE TITLE
Remove randomness from test_roundtrip

### ISSUE THREAD

**Issue by arai-a** [binast/binjs-ref#200]
having randomness in testsuite is bad :P
it tends to overlook failure.

**Comment by Yoric** [comment]
Yes, I added it because test_roundtrip lasts too long on travis and gets killed.

I'm open to other ideas :)

**Comment by arai-a** [comment]
this is blocking me from adding more testcases, because the newly added test won't be executed in most case.
we just should remove unnecessary tests to reduce the time.
