### ISSUE TITLE
Investigate having LiteralTrueExpression and LiteralFalseExpression

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#27]
We currently have `LiteralBooleanExpression`, so each boolean literal takes 1 byte of content and 1 varnum of grammar index. We could replace it with `LiteralTrueExpression` and `LiteralFalseExpression` to get rid of the byte of content, at the risk of increasing the grammar index to 2 bytes in some cases.

**Comment by sendilkumarn** [comment]
Is there any specific way to approach this issue, (for a newbie)

**Comment by Yoric** [comment]
So, one way to do this:

1. patch draft.webidl, to replace the definition of `BooleanLiteral` with a typedef containing `TrueLiteral` and `FalseLiteral`;
2. patch the implementation of `ToShift` and `FromShift` to replace instances of `BooleanLiteral` with `TrueLiteral` and `FalseLiteral`;
3. use the example `compare_compression` to gather statistics.

Now, this would not result in landable code, but having the statistics would help us find out whether this is a dead end, which would be a good start :)

**Comment by sendilkumarn** [comment]
sure let me try this thing.

**Comment by Yoric** [comment]
Note : draft.webidl just moved to spec/es6.webidl.

**Comment by sendilkumarn** [comment]
Here we go 🎉  (50% size reduction)
```
LiteralTrueExpression:
Entries: 28194 (0.31%)
Max entries per file: 1
Own bytes: 28194 (0.09%)

LiteralTrueExpression []
Entries: 28194 (0.31%)
Own bytes: 28194 (0.09%)
Shallow bytes: 28194 (0.09%)
Total bytes: 28194 (0.09%)

LiteralFalseExpression:
Entries: 19280 (0.21%)
Max entries per file: 1
Own bytes: 19280 (0.06%)

LiteralFalseExpression []
Entries: 19280 (0.21%)
Own bytes: 19280 (0.06%)
Shallow bytes: 19280 (0.06%)
Total bytes: 19280 (0.06%)

LiteralBooleanExpression:
Entries: 47474 (0.52%)
Max entries per file: 1
Own bytes: 47474 (0.14%)
Shallow bytes: 94948 (0.29%)
Total bytes: 94948 (0.29%)

LiteralBooleanExpression [value]
Entries: 47474 (0.52%)
Own bytes: 47474 (0.14%)
Shallow bytes: 94948 (0.29%)
Total bytes: 94948 (0.29%)
```

**Comment by Yoric** [comment]
So we improved by a very thin factor 0.0012. We'll focus on larger gains :)

Thanks for the benchmark, @sendilkumarn !
