### ISSUE TITLE
Test compression vs. gzip

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#295]
A long time ago, our objective was to achieve size parity with gzip, rather than brotli.

At some point, during one of the many redefinitions of V2, we silently switched target. I wonder if we have reached our first objective.

I'd like to complete our size test with gzip compression.

@vdjeric could you handle this?

**Comment by vdjeric** [comment]
Using the early-flush corpus and the "sizes.py aging" measurement:
- I measured HEAD revision of binjs-ref (ebae874acf842583d6189ee93a43a31f58589041). It's a step in the right direction: 6% size overhead vs Brotli, not counting custom dictionary. According to the spreadsheet, this is still worse than entropy-0.3 but I think that release did not roundtrip.
- Same HEAD measured vs gzip: entropy is a 15% size improvement over gzip, not counting custom dictionary size
- All results are in https://docs.google.com/spreadsheets/d/1n2WZIxy_aLY7LuueQJJAPxa0PiemMOl9kzttSw8iK-8/edit#gid=0

**Comment by vdjeric** [comment]
I'll close this issue out unless you folks have any objections?

**Comment by Yoric** [comment]
Sounds good.

Thanks!
