### ISSUE TITLE
Re-use AST context in compressing substreams like identifier indexes

### ISSUE THREAD

**Issue by dominiccooney** [binast/binjs-ref#303]
The decoder *has* AST context when it reads external streams, but the only context we use when compressing those streams is the static split by kind (identifiers versus string literals etc.) Adapt one of the contextual off-the-shelf algorithms to take a context which isn't the preceding identifier stream content but provided by the AST decoder.

For example, I've done some experiments with adapting sorted context symbol ranking to use the AST ancestor chain as context instead of preceding text and it seems very effective (although I haven't isolated it to identifiers, but I can try that.)

**Comment by Yoric** [comment]
This sounds related to https://github.com/binast/binjs-ref/issues/293, right?

**Comment by Yoric** [comment]
Since you self-assigned this, can I assume that you're actively working on it? If so, I'm putting #293 on hold and I'll be happy to hand it to you if you're interested.

**Comment by dominiccooney** [comment]
> @dominiccooney, since you self-assigned this, can I assume that you're actively working on it?

I've only been thinking about it, and I won't get to it this week. Let me dup this into #293.

I think #293 and this are similar, maybe slightly different. If I understand #293, it is to bring some identifiers into the main probability model. My idea here was to take context and push it out to the stream compressor. Both would provide context and serve the same aim. It's possible I don't understand #293 in detail.
