### ISSUE TITLE
Reduce sparsity of shared indices

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#304]
For the moment, we represent references to user-extensible dictionaries as follows:

- values `[0,  length of the shared dictionary[` are reserved for references to the shared dictionary;
- values `[length of the shared dictionary, ...[` are references to the prelude dictionary.

The first segment is very sparse, while the second is fully dense. We should find a way to make both segments dense, to improve compression.

**Comment by Yoric** [comment]
One way to do this:

- reserve values `[0, length of the prelude dictionary[` for references to the prelude dictionary;
- use values `[length of the prelude dictionary, length of the prelude dictionary + number of shared dictionary items decoded so far[` to reference values in the shared dictionary item that have already been decoded at least once;
- whenever we encounter a reference `r >= length of the prelude dictionary + number of shared dictionary items decoded so far`, we
    - take `r - length of the prelude dictionary + number of shared dictionary items decoded so far` as the index into the shared dictionary;
    - increase `number of shared dictionary` by 1;
    - use the slot of `[length of the prelude dictionary, length of the prelude dictionary + number of shared dictionary items decoded so far[` we have just added for the value we have just fetched.

**Comment by dominiccooney** [comment]
I tried simply writing a preamble to the number stream indicating which indices were in use with a bit-serialized binary tree and collapsing values into a contiguous range. This is not useful, for example on property keys this mostly resulted in a 1% blow-up.

This isn't the idea described above, but it is what I wanted to try in the context of #256 which I think @yoric edited in the list as this issue. I'm done with that; I'll leave this issue open for others to decide whether to try #issuecomment-463973912

**Comment by Yoric** [comment]
@dominiccooney I take it that the technique you tested proves not useful for any of the content streams?

**Comment by Yoric** [comment]
I'll try and implement the technique described above and see whether it has any benefit.

**Comment by Yoric** [comment]
Experimenting with the strategy expressed at https://github.com/binast/binjs-ref/issues/304#issue-410682659. The following results are based on a version that I have **not** attempted to roundtrip yet:

Protocol
```sh
$ cargo run --release --bin binjs_generate_prediction_tables -- --in tests/data/facebook/single/*.js --out /tmp/binjs/facebook-defrag/dict/
$ cargo run --release --bin binjs_encode -- --in tests/data/facebook/single --out /tmp/binjs/facebook-defrag/ advanced entropy --dictionary /tmp/binjs/facebook-defrag/dict/dict.entropy --split-streams
$ cargo run --release --example investigate_streams -- --compare-to-bzip /tmp/binjs/facebook-defrag/
```


File | raw (b) | brotli (b) |  Improvement vs. https://github.com/binast/binjs-ref/issues/302
-- | -- | -- | --
js | 43134534 | 8016723 | 0.00%
binjs | 7121173 | 7081239 | 4.91%
floats.content | 488007 | 150636 | 5.85%
identifier_names.content | 2600472 | 1087707 | 4.16%
list_lengths.content | 1986033 | 549769 | 14.73%
property_keys.content | 1943147 | 1266769 | 6.43%
string_literals.content | 2339622 | 1430863 | 5.82%
unsigned_longs.content | 449125 | 96121 | 27.84%

I'll try to cleanup and roundtrip this, but if it works, it's a pretty nice improvement.

**Comment by Yoric** [comment]
Well, as far as I can tell, the numbers are solid and it now roundtrips.

Not quite ready to open a PR, but code is here: https://github.com/Yoric/binjs-ref/tree/entropy-0.4-sparsity-2 .
