### ISSUE TITLE
No entropy-0.3.4 tag?

### ISSUE THREAD

**Issue by vdjeric** [binast/binjs-ref#314]
@Yoric  I want to re-measure latest release with gzip & brotli, but I don't see any tagged releases newer than 0.3.3. Should I just use latest rev?

**Comment by vdjeric** [comment]
Are any of your entropy-0.4-* branches ready for measurement?

**Comment by Yoric** [comment]
To be honest, the only reason for which I haven't tagged anything recently is that I didn't find a convincing tag naming scheme. Perhaps I should tag `entropy-0.4-pre-1`, or something such.

If you want something right now, you may use 11ed5f355b96780183f7706d431c3e131734c41d.

**Comment by vdjeric** [comment]
I'm ok with any naming scheme :)

**Comment by Yoric** [comment]
There's now a tag https://github.com/binast/binjs-ref/releases/tag/entropy-0.4-pre-1.
