### ISSUE TITLE
Remove untagged tuple

### ISSUE THREAD

**Issue by arai-a** [binast/binjs-ref#329]
Untagged tuple is not used.
We should remove it.

**Comment by Yoric** [comment]
The objective of this work is to:

- inline the contents of [this method](https://github.com/binast/binjs-ref/blob/061ff474d891e3c065fa0837f99f0739f6b11767/crates/binjs_io/src/simple.rs#L326) into its (only) caller `tagged_tuple`, a few lines below;
- get rid of 
  - `TokenReader::enter_untagged_tuple_at`
  - `TokenReader::exit_untagged_tuple_at`
  - all the tests that test specifically these methods
- fix whatever breaks :)
