### ISSUE TITLE
WTF-8 escaping is not roundtripping safely

### ISSUE THREAD

**Issue by RReverser** [binast/binjs-ref#350]
Consider source containing one of the characters that go through WTF-8 escape e.g. `\u007F` generated by:

```js
fs.writeFileSync('temp.js', 'let s = "\u007F;";');
```

Then the `temp.js` will contain:
```js
let s = ";";
```

If you try to encode and decode it again, you will currently get:
```js
let s="007F007F;"
```

I believe this is not the expected outcome and is probably caused by the fact that `escapeWTF8` is used on the ASTs retrieved from Shift parser, but there is no `unescapeWTF8` on the result of Shift codegen.

@arai-a tentatively assigning to you, as I believe you're the most knowledgeable in this area of the codebase.

**Comment by arai-a** [comment]
same as https://github.com/binast/binjs-ref/issues/260

**Comment by RReverser** [comment]
Oh sorry for the duplicate.
