### ISSUE TITLE
Build error with latest rustc-nightly

### ISSUE THREAD

**Issue by vdjeric** [binast/binjs-ref#405]
error: Could not compile `binjs_es6`.

error: #[serde(tag = "...")] can only be used on enums
     --> /home/vdjeric/binjs-ref/target/release/build/binjs_es6-4ffd3340009ce9fc/out/ast.rs:23849:5
      |
23849 | pub struct Null {
      |     ^^^^^^

error: #[serde(tag = "...")] can only be used on enums
     --> /home/vdjeric/binjs-ref/target/release/build/binjs_es6-4ffd3340009ce9fc/out/ast.rs:24011:5
      |
24011 | pub struct ArrayAssignmentTarget {
      |     ^^^^^^

error: #[serde(tag = "...")] can only be used on enums
     --> /home/vdjeric/binjs-ref/target/release/build/binjs_es6-4ffd3340009ce9fc/out/ast.rs:24234:5
      |
24234 | pub struct ArrayBinding {
      |     ^^^^^^

**Comment by Yoric** [comment]
This was fixed some time ago.
