### ISSUE TITLE
Split crates

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#52]
Everything is in a single crate, but we could split as follows:

- `binjs_core`, containing everything needed to deal with syntaxes:
  - checking for consistency, completeness;
  - annotator traits;
  - deanonymizing;
  - defining natively;
  - reading from webidl;
  - exporting to webidl;
  - exporting to C++ parsers (as an example);
  - exporting to Rust parsers (as an example);
  - exporting as a Rust native definition of library (as an example);
- `binjs_library`, depending on `binjs_core`, containing 
  - the Rust definition of ES6 as a library, including annotator;
      (possibly generated by `binjs_core`)
- `binjs_coding`, depending on `binjs_core`, containing
  - encoding, decoding;
  - definition of the TokenReader and TokenWriter traits;
- `binjs`, depending on all the above
  - the various implementations of TokenReader, TokenWriter;
  - actual tools for encoding, decoding, benchmarking.

**edit** Updated, following @nox' suggestion.

**Comment by nox** [comment]
IMO one of them should be `binjs`.

**Comment by Yoric** [comment]
Fair enough. Updated.
