### ISSUE TITLE
Make the memory use of Node (as used by `Shift`) parameterable

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#74]
We probably want this as an argument to the `Shift` functions. Either that or an environment variable `BINAST_NODE_MAX_OLD_SPACE_SIZE`.

**Comment by sendilkumarn** [comment]
This can be closed right

**Comment by Yoric** [comment]
Fixed by 1db3b3b4c87855dc31d00d4259bcb063cbf253ce.
